### ISSUE TITLE
Bundling mutliple spec files at once (microservices)

### ISSUE THREAD

**Issue by szero2one** [Redocly/openapi-cli#104]
Hi, first of all, awesome job on putting this together. It's really quite useful and interesting.

In your documentation you state: "_You can bundle your OpenAPI 3 definition into a single file (this may be important for certain tools that lack multifile support)._"

What I'm wondering about specifically is support for bundling multiple files. If you're developing in the cloud native paradigm, then having multiple (micro)services is the default. In this scenario, it would be really useful to have

1. Some way to support multiple files. I'm thinking the ability to input a folder path of spec files (already with the right name): e.g. `openapi bundlemany --output <output/path> <input/path>` would be a convenient way here.
2. Assuming step 1 is handled somehow, it would be great if it was added to the documentation section so that people in the future will have easy and convenient access to it. 

Thank you guys so much for developing this. Hope this is somewhat useful.

**Comment by knidarkness** [comment]
Hi @szero2one! 

First of all, I'm glad that you liked our tool!

So, your idea is basically to bundle several different OpenAPI specs into one? That might be useful for microservices/FaaS platforms, but there's a problem that there might be some conflicting information, e.g. in the `servers` section, or `security` / `info`. I'm not sure yet, what is the good way to handle that, so if you have any suggestions, they will be welcome :)

**Comment by adamaltman** [comment]
I think it may be about making multiple bundled output files (one per root)?

**Comment by RomanHotsiy** [comment]
@szero2one could you clarify what it is about?

If you want to map multiple input files to multiple output files you can do it right now. Just provide multiple inputs or even use glob syntax (`openapi bundle definitions/* -o dist`)

Or is it about merging multiple openapi definition into one?

**Comment by szero2one** [comment]
So, indeed, it's about making multiple bundled output files. Due to the folder holding an increasing number of microservice definitions, defining multiple inputs quickly becomes a hassle. The global syntax mentioned above is exactly what I was looking for (recommend adding it to the docs). Unfortunately, when trying it according to the example above, I get the following error: `Error: ENOENT: no such file or directory` Getting this feature would greatly improve the tools usability for the microservice usecase. I appreciated your consideration and support. Keep up the great work!

**Comment by adamaltman** [comment]
Have you defined the `.redocly.yaml` file? I just tried it and it is working for me. Here is an example:

```
git:(master) openapi bundle -o dist
Created a bundle for openapi/auth-service.yaml at dist/auth-service.yaml
Created a bundle for openapi/dashboard.yaml at dist/dashboard.yaml
Created a bundle for openapi/inline.yaml at dist/inline.yaml
Created a bundle for openapi/merchants.yaml at dist/merchants.yaml
Created a bundle for openapi/offline.yaml at dist/offline.yaml
Created a bundle for openapi/pricing.yaml at dist/pricing.yaml
```

**Comment by RomanHotsiy** [comment]
@adamaltman I think this is the issue:

> Due to the folder holding an increasing number of microservice definitions, defining multiple inputs quickly becomes a hassle. 

--------

> Unfortunately, when trying it according to the example above, I get the following error: Error: ENOENT: no such file or directory 

@szero2one could you provide more details? What OS are you on? Could you show an `openapi bundle` command you use?

**Comment by szero2one** [comment]
@RomanHotsiy indeed, that's correct. Ideally, there would be no need to add the definitions in the `.redocly.yaml` file. Something like this would be preferable: `openapi bundle services/* -o dist`. However, your suggestion @adamaltman is at least better than the current implementation - so thanks for that suggestion as well.

**Comment by RomanHotsiy** [comment]
That's because of PowerShell globbing works differently, see https://stackoverflow.com/q/43897242/1749888
