### ISSUE TITLE
Code snippets in error messages sometimes are too big

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/openapi-cli#113]
Take for example missing `version` field in the definition like below:

```
openapi: 3.0.1
info:
  title: Some API
  description: "very long single-line description spanning multiple lines if wrapped. All the newlines are encoded \n directly here ......
# ....
```

If you validate this file it will produce:

```
[1] index.yaml:2:1 at #/info/version
The field 'version' must be present on this level.

2| info:
3|   title: Some API
4|   description: "very long single-line description spanning multiple lines if wrapped. All the newlines are encoded \n directly here .....
```

Description line is not stripped and when wrapped by terminal takes too much vertical space while not being useful.

Additional idea may be to not output the whole level `on this level`-errors , just a few first fields instead.

**Comment by adamaltman** [comment]
This was fixed.
