### ISSUE TITLE
URLs should be able to contain relative references

### ISSUE THREAD

**Issue by stevenj** [Redocly/openapi-cli#125]
Currently if a URL does not start with https:// or http:// a validation error is thrown saying:
```
[1] v1/auth/newcustomer.oas3.yml:72:9 at #/paths/['/auth/newcustomer']/post/externalDocs/url
url must be a valid URL

70|         Must have a valid appToken for the request to be processed.
71|       externalDocs:
72|         url: "./API/flows/NewCustomer-Flow.html"
73|         description: New Customer Message Flow
74|       requestBody:

Error was generated by oas3-schema/external-docs rule.
```

But it is valid for externalDocs and License  URL's to have relative references.
See: 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#relativeReferences
https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by adamaltman** [comment]
I agree that a relative path is valid.

> Relative references are resolved using the URLs defined in the Server Object as a Base URI.

I wonder should your url be: "/API/flows/NewCustomer-Flow.html" and can you confirm whatever your server(s) is that your `{server url}/API/flows/NewCustomer-Flow.html` exists?

**Comment by stevenj** [comment]
No it actually doesn't exist at the server URL.  

Currently there is a disparity between the official spec for OpenAPI3 and how both Redoc2 and Swagger UI render it.  The spec says a relative URL should be relative to the servers in the server list.  But, at least for the `externalDocs:` both swagger UI and redoc2 use the URL of the web page embedding the openapi3 viewer as the root (which in my opinion makes more sense).  And that's how i am using it in this case.

So if my `show_openapi.html` is at `my-domain.com/api/show_openapi.html`
`./API/flows/file.html` becomes: `my-domain.com/api/API/flows/file.html` and 
`/API/flows/file.html` becomes: `my-domain.com/API/flows/file.html`

Neither of which is according to the OpenAPI3 spec, but it is sensible.
Links inside markdown descriptions work the same way.

**Comment by knidarkness** [comment]
@stevenj , thank you for using `openapi-cli`. As for now, you can disable the urls validation for the externalDocs using the `.redocly.yaml` config similar to following:

```yaml
# apiDefinitions:
# ...  
lint:
# ...  
  rules:
# ...  
    oas3-schema/external-docs:
      url: off
# ...
```

And we will update the validation rules to support the relative links in relativeDocs & license url's fields.

**Comment by stevenj** [comment]
Thank you for the workaround, works as expected.
