### ISSUE TITLE
Use custom config file when bundling

### ISSUE THREAD

**Issue by Urokhtor** [Redocly/openapi-cli#126]
At the moment `openapi bundle` always uses `.redocly.yaml` as configuration source while `openapi validate` allows users to use custom config file via `--config` option. Would it be possible to add `--config` option to bundle operation as well?

For example use case imagine that you want to build API Gateway from bundled output, but you also want to host bundled output as HTML documentation. The spec defines `security` properties which you want to be visible in your HTML documentation, but you don't want them in the spec uploaded to API Gateway because you don't want to use API Gateway's security model.

The security property can be stripped out of the output via a transformer, but you would like to apply that transformer only when bundling for API Gateway. This would be possible if bundle supported custom config files.

**Workaround**

One workaround for this that I can imagine of is to put your custom `.redocly.yaml` into a folder, e.g. `api-gateway/.redocly.yaml` and then running `openapi bundle` from there. But as described above that validate already supports custom configs, I think it would be reasonable that bundle would do that as well.

**Comment by adamaltman** [comment]
@Urokhtor, Thanks for the suggestion.

🎉 🎉 🎉 

This is done now (part of 1.0.0-beta.1, see #146 ).
