### ISSUE TITLE
openapi-cli validate just crashes during validation

### ISSUE THREAD

**Issue by Ark-kun** [Redocly/openapi-cli#127]
```
$ npx @redocly/openapi-cli validate https://raw.githubusercontent.com/Ark-kun/pipelines/ba5aede77e5745922a714ec60920dc504197a8b3/sdk/python/kfp/components/structures/components.json_schema.json
npx: installed 73 in 5.813s
Will validate from URL
(node:249586) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at Object.onEnter (/usr/local/home/foo/.npm/_npx/249586/lib/node_modules/@redocly/openapi-cli/dist/visitors/rules/structural/noRefSiblings.js:25:35)
    at runRuleOnRuleset (/usr/local/home/foo/.npm/_npx/249586/lib/node_modules/@redocly/openapi-cli/dist/traverse.js:166:137)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:249586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:249586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by adamaltman** [comment]
We should give a nicer error message instead of crashing. 

From what I can tell when I look at the file it is not an OAS2 or OAS3 definition. 

```
  "$schema": "http://json-schema.org/draft-06/schema#",
```

Maybe there is some demand for JSON Schema validation. There are also many different versions of JSON Schema. OAS3.0:

> Models are defined using the Schema Object, which is an extended subset of JSON Schema Specification Wright Draft 00.

### Action items

- I made this issue: https://github.com/Redocly/openapi-cli/issues/132
- Create a polling issue to ask if we should add JSON Schema validation to this library.

**Comment by Ark-kun** [comment]
> From what I can tell when I look at the file it is not an OAS2 or OAS3 definition.

Oh, I see my mistake. I got pointed to Redocly by one of my peer saying "it would be easier to see your schema if it was shown as this Redocly example" and I just went on without thinking that while OAS3 uses JsonSchema to describe parameters, OAS is not the same as JsonScheama.

Generally, it would be nice to be able to visualize object schema not just as part of routes.

**Comment by adamaltman** [comment]
It is possible to visualize the object schema not as routes, but in our case, only if it is part of the OAS document.

**Comment by adamaltman** [comment]
I'm closing this issue. 1.0.0-beta.1 solves the error message part of the issue.

```
Something went wrong when processing https://raw.githubusercontent.com/Ark-kun/pipelines/ba5aede77e5745922a714ec60920dc504197a8b3/sdk/python/kfp/components/structures/components.json_schema.json:

  - Unsupported OpenAPI Version: undefined.
```
