### ISSUE TITLE
[Feature] ability to skip the given endpoints when bundling (preferably by regex)

### ISSUE THREAD

**Issue by karolkania** [Redocly/openapi-cli#134]
It'd be great to be able to (automatically) skip endpoints considered private when bundling for i.e. public APIs 

Let's say there are `/status` or `/healthcheck` endpoints used by monitoring tools and they are not really important from the API docs' standpoint. 

On the other hand they might be quite important, so having one OpenAPI definition one could generate two bundles:

- one for the public docs, 
- the other for internal docs (or other scenarios if building more sophisticated setup using the OpenAPI definition as a single source of truth)

Even better if this could be part of the `.redocly.yaml` file specified as regex rule(s)

**Comment by adeschamps** [comment]
I had the same goal, and I was able to achieve this using a [transformer](https://github.com/Redocly/openapi-cli/blob/master/docs/TRANSFORMERS.md). It modifies the tree by removing any operations that have `x-private: true`.

```js
// transformers.js
class ExcludePrivate {
  static get rule() {
    return 'excludePrivate';
  }

  OpenAPIPath() {
    return {
      onEnter: (node, _type, ctx) => {
        for (let key in node) {
          if (node[key]['x-private']) {
            console.log(`excluding ${key} from ${ctx.filePath}`);
            delete(node[key]);
          }
        }
      }
    }
  }
}

module.exports = [ExcludePrivate];
```

```yaml
# .redocly.yaml
lint:
  transformers: transformers.js
  rules:
    # Custom rule to exclude endpoints with `x-private: true`.
    excludePrivate: on
```
