### ISSUE TITLE
Validation fails with operation-2xx-response on callbacks

### ISSUE THREAD

**Issue by joe-gordian-software** [Redocly/openapi-cli#136]
Repro steps:
1. `npm install @redocly/openapi-cli`
1. `./node_modules/.bin/openapi validate https://raw.githubusercontent.com/Redocly/redoc/master/demo/openapi.yaml`

The output includes the following, even though the subscribe endpoint does define a 201 response:
```
[6] https:/raw.githubusercontent.com/Redocly/redoc/master/demo/openapi.yaml:493:5 at #/paths/['/store/subscribe']/post
Operation must have at least one 2xx response.

491|           description: Order not found
492|   /store/subscribe:
493|     post:
494|       tags:
495|         - store

Warning was generated by operation-2xx-response rule.
```

**Comment by joe-gordian-software** [comment]
Thank you!

**Comment by stellis** [comment]
@RomanHotsiy Has this fix landed on the Redoc.ly hosted service yet?

**Comment by RomanHotsiy** [comment]
Yes, it has landed already, you must be facing this: https://github.com/Redocly/openapi-cli/issues/145
