### ISSUE TITLE
docs: linting section

### ISSUE THREAD

**Issue by ArtFlag** [Redocly/openapi-cli#140]
Thanks for this very cool tool 🎉 

I am trying to set up custom linting rules and I found it a bit confusing, and I would like to provide feedback on the docs. 

About the `string-matcher` property:
- It does not seem to be published on [https://docs.redoc.ly](https://docs.redoc.ly)
- I did not understand where to find the possible values for the `on` field, or how to compose the value. 

On the website:
- The `https://docs.redoc.ly/cli/configuration/reference-docs/index.md` link leads to a 404.

I'd be happy to send out a PR to update once we get answers here 🙂

**Comment by RomanHotsiy** [comment]
Hey @ArtFlag,

Thanks for the issue. We are redesigning custom rules API right now so it gets much easier to write custom rules.

We should have some information on ETA until the end of the week.

I will keep you posted here.

**Comment by ArtFlag** [comment]
I love the sound of that 👍  Looking forward to the result 😍

**Comment by RomanHotsiy** [comment]
@ArtFlag we have an alpha released from this branch: https://github.com/Redocly/openapi-cli/tree/full-rewrite

Docs are not ready yet though.

**Comment by adamaltman** [comment]
@ArtFlag we released a beta, as well as beta docs too.

**Comment by adamaltman** [comment]
We got some feedback on the docs that how-to guides would be helpful. I made one for a decorator:

https://redoc.ly/docs/resources/hide-apis/

However, I need to make one for a regular rule too.
