### ISSUE TITLE
@redocly/openapi-cli@0.12.13 & 0.12.14 are broken builds

### ISSUE THREAD

**Issue by karolkania** [Redocly/openapi-cli#141]
v0.12.12 is last known to be working properly

**Comment by RomanHotsiy** [comment]
@karolkania any details?

**Comment by karolkania** [comment]
0.12.13 & 0.12.14 produce wrong bundles

**Comment by karolkania** [comment]
0.12.13 - produces undefined values, 
0.12.14 - $refs are lost when bundling

**Comment by RomanHotsiy** [comment]
It should be fixed in 0.12.15. Could you please verify?

**Comment by karolkania** [comment]
Fine now, thanks!

**Comment by RomanHotsiy** [comment]
Thanks for reporting!
