### ISSUE TITLE
Internal loader error in latest npm install

### ISSUE THREAD

**Issue by dashsatish** [Redocly/openapi-cli#158]
version used:  `@redocly/openapi-cli@1.0.0-alpha.10`
npm version: `npm@6.14.5`
Installation method: `npm install -g  @redocly/openapi-cli`  [as per README]

Error during validate:
```
$ openapi validate openapi.yaml 

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'outdent'
Require stack:
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/redocly/index.js
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/common/registry-dependencies.js
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/oas3/index.js
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/builtin.js
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/config/config.js
- /usr/local/lib/node_modules/@redocly/openapi-cli/lib/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@redocly/openapi-cli/lib/redocly/index.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/redocly/index.js',
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/common/registry-dependencies.js',
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/oas3/index.js',
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/rules/builtin.js',
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/config/config.js',
    '/usr/local/lib/node_modules/@redocly/openapi-cli/lib/cli.js'
  ]
}
```

Could you please suggest a workaround or fix this ASAP??

**Comment by benfdking** [comment]
We are  seeing a similar error when trying to use the tool with `npx`. Could it be due to the fact that `outdent` is marked as a dev dependency? 

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/9087625/86749624-4d3f1180-c035-11ea-9924-6396c9790478.png">

**Comment by benfdking** [comment]
We have found a workaround for the time being with `npx`. Just specifying an older version: 

```
npx @redocly/openapi-cli@0.12.16 help
```

**Comment by dashsatish** [comment]
@benfdking  

> We have found a workaround for the time being with `npx`. Just specifying an older version:
> 
> ```
> npx @redocly/openapi-cli@0.12.16 help
> ```

*The above workaround is what I used already to download only that specific version. IT WORKS!!!*

But,
why does the install get us a new version something like `@redocly/openapi-cli@1.0.0-alpha.10`. Is that the intent of the build?

**Comment by RomanHotsiy** [comment]
@dashsatish @benfdking we accidentally published our alpha version under the `latest` tag. This have been fixed already.

Sorry for the troubles!

**Comment by RomanHotsiy** [comment]
Btw, the latest alpha.11 fixes the issue with outdent.
