### ISSUE TITLE
Support OAS 3.1

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#160]
Version 3.1 of the OpenAPI specification was released! `@redocly/openapi-cli` should support that version.

See: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md

**Comment by hilary** [comment]
v3.1 was released on Feb 15th (wahoo!). What's the status of 3.1 support? Eager fans are eager! :smiling_face_with_three_hearts:

**Comment by adamaltman** [comment]
It would be nice to have a test OpenAPI 3.1 definition that uses the full feature set. 

I think we will have support for it by mid-April, unless someone frees up their time soon.

**Comment by sken3r** [comment]
@adamaltman any updates here?

**Comment by AlexVarchuk** [comment]
> @adamaltman any updates here?
@sken3r Hi! We added supporting OpenApi 3.1(attached in linked PR). If you have some questions or ideas for improvements please let me us.
