### ISSUE TITLE
Warn on incorrect $ref use and ease ability to resolve those $refs

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#189]
**Is your feature request related to a problem? Please describe.**
Many people don't know where it is valid to use `$refs` for resolution. The OpenAPI spec prescribes explicitly where it can be used. However, people use it in many other places. This causes frustration. And tools like `redoc` support incorrect usage for years already... 

**Describe the solution you'd like**
I'd like a mechanism to:
- warn people when `$refs` are detected (in some cases, people use them literally and they intend a property name to be `$ref` but that is rare -- they can use the ignore file to ignore such incorrect warnings); 
- resolve incorrect `$refs` that are explicitly provided (is this a type extension?), such as below... 

```
resolve-incorrect-refs:
  - info.description
  - tags.description
  - etc...
``` 
Should it also accept `*` as a wildcard value to cover everything?

**Describe alternatives you've considered**

1. People can write custom type extensions (seems too complex for the average user).
1. Doing nothing (this will just leave too many people frustrated).
1. Resolve every `$ref` and do the opposite -- explicitly define what to not resolve (do not resolve list)....

```
skip-resolving-refs:
  - info.description
  - etc..
```

**Additional context**
The `bundle` command should still be able to bundle into a correct OAS definition.

**Comment by RomanHotsiy** [comment]
We now resolve most of refs.
