### ISSUE TITLE
Consider adding an --exclude argument for Windows-compatible globbing

### ISSUE THREAD

**Issue by zeke** [Redocly/openapi-cli#193]
Hi @RomanHotsiy and @adamaltman 👋🏼 

I work on a project (I think you know the one!) that uses a command like this:

```
openapi bundle -o dist --ext=json definitions/*[!next].yml
```

We use that `[!next]` part to ignore files with `next` in their name. But this type globbing expression is not supported on Windows. At one point we discussed that this package, `openapi-cli`, could support an `--exclude` argument or similar that could be used to achieve this same effect while still supporting Windows users.

cc @jf205 @rachmari

**Comment by RomanHotsiy** [comment]
Hey @zeke,

How about properly handling globs on windows (using node glob implementation) instead of adding `--exclude`?

**Comment by zeke** [comment]
That would work. To clarify, do you mean making a change in the openapi-cli?

Or do you mean introducing a script in my project that assembles a command string and runs it in a child process or something?

**Comment by adamaltman** [comment]
@zeke We were thinking a change to the `openapi-cli` possibly like in this PR: #196 (still to-be-reviewed).

**Comment by zeke** [comment]
Ah thanks for clarifying. I haven't reviewed that PR but if the change unlocks Windows compatibility I'm for it. I can help review  https://github.com/Redocly/openapi-cli/pull/196 if needed, just let me know.

**Comment by andriyl** [comment]
fixed on #196

**Comment by RomanHotsiy** [comment]
Hey @zeke! We forgot to ping you earlier. 🙈 

It should work in `v1.0.0-beta.16`.

**Comment by zeke** [comment]
Sweet! Thank you.
