### ISSUE TITLE
Resulting file is not dereferenced after running command 'openapi bundle --dereferenced' 

### ISSUE THREAD

**Issue by prooles** [Redocly/openapi-cli#222]
**To Reproduce**
1. Given this `openapi.yaml` file in root with $ref's in it
2. Run 'openapi bundle --dereferenced  --output bundle --ext json openapi.yaml'
4. See resulting file

**Expected behavior**
The resulting file should be dereferenced

**Comment by adamaltman** [comment]
@RomanHotsiy you fixed this, right?

**Comment by RomanHotsiy** [comment]
Yes, fixed in https://github.com/Redocly/openapi-cli/pull/273
