### ISSUE TITLE
Preview-docs command not hot-refreshing on file changes

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#231]
**Describe the bug**

While running `preview-docs`, I edit the OpenAPI definition and the browser doesn't hot reload/refresh automatically.

**To Reproduce**
1. Clone the openapi-starter repo.
2. Run `openapi preview-docs`.
3. Load the browser and browser to a specific operation.
4. Go back to your IDE and change the operation's description.
5. Go back to the browser, and notice it doesn't update automatically.

**Expected behavior**
I expected hot reload upon changes (I'm sure it used to do this correctly in the past).

**Logs**
n/a

**OpenAPI definition**

**`openapi-cli` Version(s)**

1.0.0-beta.25

**`Node.js` Version(s)**
What version of `node.js` are you using?

12.18.2

**Additional context**

none

**Comment by mjpieters** [comment]
I was just diagnosing this very problem. The issue is that `hot.js` is not copied from `src/commands/preview-docs/preview-server/hot.js` to `lib/commands/preview-docs/preview-server/hot.js`.

The work-around is to copy it manually:

```sh
$ cp node_modules/@redocly/openapi-cli/src/commands/preview-docs/preview-server/hot.js \
  node_modules/@redocly/openapi-cli/lib/commands/preview-docs/preview-server/
```
