### ISSUE TITLE
Ability to dereference $referenced properties without adding them to the schemas object

### ISSUE THREAD

**Issue by Kerry-at-VIP** [Redocly/openapi-cli#238]
`**Is` your feature request related to a problem? Please describe.**

I have many properties that are duplicated through the oas3 spec doc that I'd like to define separately to keep DRY.

However, when I use $ref's to do this, the openapi-cli build process automatically adds these properties to the `schemas` object in the output spec yaml, which results in the consuming developers seeing these properties in the "schemas" section of the generated html docs.

The resulting spec html has the `schemas` section cluttered with these one-off properties.

**Describe the solution you'd like**

Perhaps, a way to "flatten" the $referenced objects into the result file.
In other words, copy the properties from the referenced object, and paste into all of the places where it is referenced in the parent; (instead of creating a schemas property and referencing that).

**Describe alternatives you've considered**

I have read through all of the openapi-cli documentation, and am considering writing a decorator for this, but wanted to get feedback before going down that road.

**Additional context**

Alternatively - now I'm wondering if it may be cleaner to keep all of these misc properties in a single separate file (e.g. common.yaml) may keep things more organized; perhaps even nested under a master object. For example:

```
Common:
  SalesRepID:
    type: string
    maxLength: 5
```
And then reference with `$ref: ../schemas/Common.yaml#/common/SalesRepID`

Nope - I just tested it and the openapi-cli build seems to ignore the parent "Common" object, and just puts "SalesRepID" in the resulting schemas object in the output file

**Comment by adamaltman** [comment]
@Kerry-at-VIP, thank you for opening an issue! :tada: We appreciate it.

We have a feature called "dereferenced" which may be doing what you describe. 

https://redoc.ly/docs/cli/commands/#bundle

Try the `--dereferenced` argument

Also, the `Common` object in your example might be invalid.

**Comment by Kerry-at-VIP** [comment]
Hi Adam - I tested the `--dereferenced` argument.

That is close to what I'm looking for.
I'd like the ability to only dereference some $ref'd objects though, not all.

Perhaps by adding an extension like `x-dereferenced` to the $ref'd object.

Also - it appears that the build still puts the referenced objects into the `components/schemas` section of the document, even though they have been dereferenced.

**Comment by adamaltman** [comment]
So the idea is:

1. Paths may have references to schema.
2. Each of those schemas should be dereferenced (no references to other schemas from schemas).

Is that right? I like it.

**Comment by Kerry-at-VIP** [comment]
I think I was going about building the schema models in an overly-complex way.
I'm embarrassed to say I didn't understand that you could not only $ref to a file, but also to a relative component in that file.
Armed with this technique, I'm re-working my schema model, and not sure this issue request I opened makes any sense.
I'm going to close this and open a new one that hopefully makes more sense.
Thanks for your indulgence.
