### ISSUE TITLE
"openapi preview-docs" returning http 404 "Something went wrong..." trying to display multi-file response example

### ISSUE THREAD

**Issue by Kerry-at-VIP** [Redocly/openapi-cli#243]
**Describe the bug**
When running the http preview server with `openapi preview-docs`, I get the following error:

```
Something went wrong...

Error downloading http://127.0.0.1:8080/examples/PreferencesGetProfileInfoForSM.json HTTP ERROR 404
Stack trace
Error: Error downloading http://127.0.0.1:8080/examples/PreferencesGetProfileInfoForSM.json 
HTTP ERROR 404
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:29:28051
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:80:36080

Error: HTTP ERROR 404
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:29:28051
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:80:35658

ReDoc Version: 2.0.0-rc.45
Commit: aa53416d
```

**To Reproduce**
Multi-file yaml structure:
```
openapi
├── components
│   ├── examples
│   ├── requestBodies
│   ├── responses
│   ├── schemas
│   └── securitySchemes
├── paths
└── openapi.yaml
```
In `/openapi/components/responses`, I have (for example):
```yaml
description: >
  **OK**: Returns the salesrep's route profile data
content:
  application/json:
    schema:
      $ref: ../schemas/Preferences.yaml
    example:
      $ref: '../examples/PreferencesGetProfileInfoForSM.json'
```
In `/openapi/components/examples` I have the example `PreferencesGetProfileInfoForSM.json` file:
```json
{
  "SM": "B03",
  "Preferences": {
    "NextInvoiceNumber": 130002
  }
}
```
Run `openapi preview-docs` and browse to `http://127.0.0.1:8080`

**Expected behavior**
If I paste the example into the response `.yaml` everything works fine. This works fine:
```yaml
description: >
  **OK**: Returns the salesrep's route profile data
content:
  application/json:
    schema:
      $ref: ../schemas/Preferences.yaml
    example:
#      $ref: '../examples/PreferencesGetProfileInfoForSM.json'
      {
        "SM": "B03",
        "Preferences": {
          "NextInvoiceNumber": 130002
        }
      }
```

**OpenAPI definition**
`openapi: 3.0.3`
`.redocly.yaml`:
```yaml
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    info-license:
      severity: off
    tag-description:
      severity: off
```

**`openapi-cli` Version(s)**
`"@redocly/openapi-cli": "^1.0.0-beta.25"`

**`Node.js` Version(s)**
What version of `node.js` are you using?
`npm --version`: `6.14.8`

**Comment by adamaltman** [comment]
I think it could be related to this: https://redoc.ly/docs/resources/ref-guide/#incorrect-examples-by-reference

The `PreferencesGetProfileInfoForSM.json` file contents look incorrect. It would expect a structure like:

```json
"value": {
  the actual example goes here
}
```

**Comment by adamaltman** [comment]
Unrelated: we did fix a bug in 1.0.0-beta.29. Please update to that version. It shouldn't impact this though.

**Comment by Kerry-at-VIP** [comment]
Hi Adam - Thanks for the response!

According to the [Swagger OAS3 documentation](https://swagger.io/docs/specification/adding-examples/), for a `response`, you can either provide a single `example`, or multiple `examples` to a response.

Single `example` in response body:
```yaml
responses:
  '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        example: 
          # Properties of the referenced object
          id: 10
          name: Jessica Smith
```
Multiple `examples` in response body:
```yaml
responses:
  '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        examples:
          Jessica:
            value:
              id: 10
              name: Jessica Smith
          Ron:
            value:
              id: 20
              name: Ron Stewart
```
It appears that the difference is that with multiple `examples` you have to name each individual example, as well as provide the "value:" key.

Regardless, I just tested both techniques, and as you suggested, using the multiple `examples` technique (even though i only have one) works correctly.

Additionally, I tested and found that using the single `example:` technique works as well, but only if you provide the `value:` key (which is invalid oas3, right?):
`openapi/components/responses/ResponseExample.yaml`:
```yaml
description: >
  **OK**: Returns the salesrep's route profile data
content:
  application/json:
    schema:
      $ref: ../schemas/Preferences.yaml
    example:
      $ref: '../examples/responses/TestExample.yaml'
``` 
`openapi/components/examples/responses/TestExample.yaml`
```yaml
value:
  {
    "SM": "B03",
    "Preferences": {
      "NextInvoiceNumber": 130002
    }
  }
```
This example doesn't give the "Something went wrong" error, but is not valid per the OAS3 spec, right?

**Comment by adamaltman** [comment]
Hi Kerry, please see the specification: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#media-type-object

The Media Type Object "example" cannot use a Reference Object.

**Comment by Kerry-at-VIP** [comment]
Well shoot, that's embarassing.
I need to get more comfortable with the OAS reference specs.
Sorry about that, and thanks for the link.

**Comment by adamaltman** [comment]
@Kerry-at-VIP this catches many "experts" including myself and my teammates from time to time. We are working on a feature about this: https://github.com/Redocly/openapi-cli/issues/189
