### ISSUE TITLE
support official docker image

### ISSUE THREAD

**Issue by Oncilla** [Redocly/openapi-cli#245]
First of all, thanks for the great toolkit!
I'll be happy to contribute code, if this is something you consider doing.

**Is your feature request related to a problem? Please describe.**

Currently, there is no officially supported docker image, and I don't particularly like to install npm only to use this amazing cli tool.

**Describe the solution you'd like**

I would prefer if the openapi-cli tool would additionally be distributed as a docker image.

**Describe alternatives you've considered**

Alternatively, openapi-cli could be packaged as standalone executable for each target platform.
But that means more maintenance overhead for releasing.

**Comment by adamaltman** [comment]
What do you think about this image? 

https://github.com/nodejs/docker-node/blob/master/README.md

Also, I did see this: https://github.com/vercel/pkg (which may be useful for packaging standalone executables)

**Comment by Oncilla** [comment]
So, I have a working Dockerfile that you can just put in the project root:

```
FROM node:alpine

WORKDIR /build

COPY webpack.config.ts tsconfig.json tsconfig.build.json /build/
COPY package.json package-lock.json /build/
COPY packages /build/packages

RUN npm ci --no-optional --ignore-scripts
RUN npm run webpack-bundle

FROM node:alpine

WORKDIR /bin
COPY --from=0 /build/dist/bundle.js /bin/openapi-cli

ENTRYPOINT [ "node", "openapi-cli"]
```

I guess the question is more whether you would be willing to support and maintain this.
In particular, host this at https://hub.docker.com/u/redocly

**Comment by Oncilla** [comment]
Opened PR for this #247

Any feedback is welcome.

**Comment by adamaltman** [comment]
We'll take action on the PR next week.
