### ISSUE TITLE
Duplicated mapping key

### ISSUE THREAD

**Issue by tjperry07** [Redocly/openapi-cli#246]
**Describe the bug**
When running preview docs `openapi preview-docs dist/public-cloud-api.yaml` there is a duplicated mapping key `codeSample:`

**To Reproduce**
1. Copy and paste the theme options from https://redoc.ly/docs/cli/configuration/reference-docs/#theming
2. Run the preview-docs command `openapi preview-docs dist/public-cloud-api.yaml`
3. Returns the following error:

```bash
(node:3356) UnhandledPromiseRejectionWarning: Error: Error parsing config file at `.redocly.yaml`: duplicated mapping key at line 175, column -68:
        codeSample:
        ^
```

**Expected behavior**
A preview of the documentation with the theming options from `.redocly.yaml`

**Logs**
N/A

**OpenAPI definition**
OpenAPO 3.0

**`openapi-cli` Version(s)**
What version of `openapi-cli` are you using?  `1.0.0-beta.29`

**`Node.js` Version(s)**
What version of `node.js` are you using? `v12.18.3`

**Additional context**

**Comment by adamaltman** [comment]
Thanks. The bug is in the docs here: https://redoc.ly/docs/cli/configuration/reference-docs/#theming (the `codeSample` key appears twice (near the bottom).#241 

@skadinna can you check it out?

**Comment by skadinna** [comment]
Hi, I've pushed a fix [here](https://github.com/Redocly/marketing-site-portal/pull/188/commits/f8046e6bbcb0d039a10ea22290f2d0934ae8e659) - it looks like there's a typo in "constraints" on that theming page, so I've changed that, too.
