### ISSUE TITLE
Not showing error when file upload fails

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/openapi-cli#248]
**Describe the bug**
OpenAPI-CLI not showing an error when file upload fails using the `push` command. 
There is no feedback on a openapi push command.

**Expected behavior**
I would like to be able to get the success/failure status as well as a link to the snapshot build of the push.

**Logs**
n/a

**OpenAPI definition**
n/a

**`openapi-cli` Version(s)**
1.0.0-beta.29

**`Node.js` Version(s)**
12.20.1

**Additional context**
None.

**Comment by jacobator** [comment]
> a link to the snapshot build of the push

this will not be done because snapshot links are created in a separate job, it is not part of the push command
