### ISSUE TITLE
Alternative filename spacers when spliting api paths other than @.

### ISSUE THREAD

**Issue by kleyow** [Redocly/openapi-cli#260]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my filenames deviate too far from the standard of my files.
`paths/resource@{parameter}.yaml` 

**Describe the solution you'd like**
It would be nice if you could specify the spacer used when splitting openapi specifications.
Instead of `@` I would like to specify `_` or `-` through the command 
i.e `openapi split api.yaml --outDir myDir --spacer _`

results in `paths/resource@{parameter}.yaml` 

Bundle would need an option to interpret the spacer aswell 
i.e `openapi bundle .... --spacer _`

**Describe alternatives you've considered**
None.

**Additional context**
I believe the path file name logic is located here
https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/utils.ts#L90

**Comment by adamaltman** [comment]
The file has probably changed since you created the issue:

https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/utils.ts#L68

**Comment by adamaltman** [comment]
I'm not sure the reason bundle would need to interpret the spacer.

**Comment by adamaltman** [comment]
I like this idea. I think instead of "spacer" it should be named "separator".

**Comment by jasonbstanding** [comment]
We're having a similar issue, in that our object files are named `foo.bar.baz.v1.yaml` - we've verified that the bundler behaves sensibly if we rename the files/references to `foo-bar-baz-v1.yaml`, however it would be nice(r) for the bundler not to assume that the first period it encounters is the filename and everything after it is the extension.

As it is, `foo.bar.baz.v1.yaml`, `foo.bar.qux.v1.yaml` and `foo.quux.quuz.v1.yaml` get folded into the components collection as `foo-1`, `foo-2` and `foo-3` - along with a load of "duplicate name" errors.

**Comment by adamaltman** [comment]
@jasonbstanding I think your issue is a bug (it's different from this issue which is a feature request about the `split` command). I opened this issue you may want to follow: https://github.com/Redocly/openapi-cli/issues/560

**Comment by RomanHotsiy** [comment]
I would change default value to `_` too.

**Comment by RomanHotsiy** [comment]
@TylerRick thanks for so detailed write up.

We'll just consider using `/` as a separator 🙌

We used `@` in the first place due to historical reasons, a few years ago our tool did not use $refs and relied on the directory structure to combine paths. In that case having flat file system was much easier.
I think it was just a "tunnel vision" to replace `@` with `_` and not with `/`. But I'll have to double-check if we can safely do it and if there are not any other reasons for this 😄
