### ISSUE TITLE
openapi lint --version does not lint

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#263]
**Describe the bug**

Running `openapi lint --version` returns the version but does not actually `lint`.

**To Reproduce**
1. Given our `openapi-starter` `.redocly.yaml` file and OpenAPI file(s)
2. Run this command with these arguments... `openapi lint --version`
4. See only the version is returned, and the lint doesn't execute.

**Expected behavior**
I expected both the version and the lint to execute.

**Logs**
```
adam@adam-Leopard-Extreme:~/demo$ openapi lint --version 
1.0.0-beta.35
adam@adam-Leopard-Extreme:~/demo$ openapi lint
validating /home/adam/demo/openapi/openapi.yaml...
/home/adam/demo/openapi/openapi.yaml: validated in 647ms

Woohoo! Your OpenAPI definition is valid. 🎉
```

**`openapi-cli` Version(s)**

1.0.0-beta.35

**`Node.js` Version(s)**
12.6

**Additional context**
none

**Comment by jacobator** [comment]
@adamaltman this is expected behaviour IMO. For example `npm` works the same way:
```
$ npm -v 
7.5.3
``` 

```
$ npm install -v 
7.5.3
```
