### ISSUE TITLE
References to examples become invalid after bundle

### ISSUE THREAD

**Issue by league55** [Redocly/openapi-cli#274]
**Describe the bug**
Given: an openAPI documentation split into several files. Each sub-file has `components` section with `schemas` and `examples`.
When: `openapi bundle index.yaml -o finalBig.yaml` is called
Then: `schemas` are copied into `finalBig.yaml` components section, but examples are not.  Because of this, all `$ref: '#/components/examples/example_name'` become invalid.

**To Reproduce**
File structure:
```
.
├── helloWorld.yaml
├── index.yaml
└── openapi.yaml
```

index.yaml:
```
openapi: 3.0.3
info:
  title: 'test'
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /helloWorld:
    $ref: 'helloWorld.yaml#/path/hello'
```
helloWorld.yaml
```
path:
  hello:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/a'
            example:
              $ref: '#/components/examples/b'
      responses:
        '201':
          description: Created

components:
  schemas:
    a:
      type: object
  examples:
    b:
      value:
        asdf: asdf

```

1. Executing `openapi bundle index.yaml -o openapi.yaml`
2. openapi.yaml looks like:
```
openapi: 3.0.3
info:
  title: test
  version: 1.0.0
servers:
  - url: https
paths:
  /helloWorld:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/a'
            example:
              value:
                asdf: asdf
      responses:
        '201':
          description: Created
components:
  schemas:
    a:
      type: object
```

**Expected behavior**
I would expect `components` to be something like:
```
components:
  schemas:
    a:
      type: object
  examples:
    b:
      value:
        asdf: asdf
```

**`openapi-cli` Version(s)**
 openapi --version: 1.0.0-beta.41

**`Node.js` Version(s)**
v12.20.1

**Additional context**
Am I doing something wrong here?

**Comment by adamaltman** [comment]
> Am I doing something wrong here?

Yes. This:

> Each sub-file has components section with schemas and examples.

OAS should have only one components section (in the root file). The root file can point to other files, but the other files should not re-declare components or schemas, etc... Some reading and samples for you:

- https://github.com/Redocly/openapi-starter
- https://redoc.ly/docs/resources/multi-file-definitions/
- https://redoc.ly/docs/resources/ref-guide/

**Comment by league55** [comment]
Thank you!
I was searching for this information before asking, but apparently, I looked for it in the wrong places.
