### ISSUE TITLE
Add basic support for OpenAPI 3.1 (Phase 1)

### ISSUE THREAD

**Issue by Marshevskyy** [Redocly/openapi-cli#276]
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0

**Acceptance criteria:**
* it should work with OAS 3.1. without supporting all-new features (new features from 3.1 will be done in a separate issue https://github.com/Redocly/openapi-cli/issues/277)
* update Redoc https://github.com/Redocly/redoc/issues/1547

**Comment by AlexVarchuk** [comment]
It will work after the release of this [PR](https://github.com/Redocly/openapi-cli/pull/280). And we only should update version `openapi-core` in `redoc` and `reference-doc` libs.
Tested it locally:
redoc:
![Redoc](https://user-images.githubusercontent.com/14113673/118270264-7687c400-b4c8-11eb-9b6b-4590fd9a7d54.png)
reference-docs:
![reference-docs](https://user-images.githubusercontent.com/14113673/118270357-9fa85480-b4c8-11eb-95e5-3b8c964e9677.png)

**Comment by AlexVarchuk** [comment]
Still need upgrade `redoc` lib.
