### ISSUE TITLE
Add advanced support for OpenAPI 3.1 (Phase 2)

### ISSUE THREAD

**Issue by Marshevskyy** [Redocly/openapi-cli#277]
Start work on in once https://github.com/Redocly/openapi-cli/issues/276 will be done

https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0

**Acceptance criteria:**
* Support all new features from OAS 3.1
* update Redoc https://github.com/Redocly/redoc/issues/1547

**Comment by AlexVarchuk** [comment]
Done. Attached linked PR.
