### ISSUE TITLE
no-empty-servers should be a warning by default

### ISSUE THREAD

**Issue by PlusMinus0** [Redocly/openapi-cli#285]
Docker image SHA: [c35ae091dd10](https://hub.docker.com/layers/redocly/openapi-cli/latest/images/sha256-c35ae091dd1026f4de1a951ad3404cc15c5e31de6e037665c2651c75ae6ca7ca?context=explore)

According to [the API](https://spec.openapis.org/oas/v3.0.0#fixed-fields) the servers field is not required therefore the cli should not throw an error by default.

| **Field Name** | **Type** | **Description**|
|---------------------|-------------|-----------------------|
|servers | [Server Object] | An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /.|

```shell
$ node /bin/openapi-cli lint api/openapi.yml
No configurations were defined in extends -- using built in recommended configuration by default.
validating api/openapi.yml...
[1] api/openapi.yml:1:1 at #/
Servers must be present.
  1 | openapi: "3.0.0"
    | ^^^^^^^^^^^^^^^^
  2 | info:
    | ^^^^^
  … | < 112 more lines >
115 |           type: string
    |           ^^^^^^^^^^^^
116 |
Error was generated by the no-empty-servers rule.
```

**Comment by adamaltman** [comment]
You were using our “recommended” configuration. You do not need to use that. You can use the minimal rule set. 

We recommend not having empty servers and we’re sticking to it. Why? The “try it” console won’t work with empty servers.

**Comment by PlusMinus0** [comment]
Now I see the hint. To set minimal without configuration file it would `openapi-cli lint --extends minimal  api/openapi.yml` work? If so, maybe that could be added to the hint. It took some time to find the rulesets and I knew, what I was looking for.
