### ISSUE TITLE
Missing     "js-yaml": "^3.14.0" dependency in cli package

### ISSUE THREAD

**Issue by jandppw** [Redocly/openapi-cli#286]
**Describe the bug**
In a project that is using js-yaml 4, `openapi bundle` fails

**To Reproduce**

- Create a project that has a dependency on `"js-yaml": "^4.0.0"`, and a dependency on `"@redocly/openapi-cli": "^1.0.0-beta.44",`
- run `npx openapi bundle`

```
bundling […]/openapi/index.yaml...
Something went wrong when processing […]/openapi/index.yaml:

  - Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead, which is now safe by default..

(node:88437) UnhandledPromiseRejectionWarning: Error: Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead, which is now safe by default.
    at Object.safeDump ([…]/node_modules/js-yaml/index.js:10:11)
    at Object.dumpBundle ([…]/node_modules/@redocly/openapi-cli/lib/utils.js:98:21)
    at Object.<anonymous> ([…]/node_modules/@redocly/openapi-cli/lib/commands/bundle.js:38:48)
    at Generator.next (<anonymous>)
    at fulfilled […]/node_modules/@redocly/openapi-cli/lib/commands/bundle.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
No crash

**Logs**
NA

**OpenAPI definition**
NA

**`openapi-cli` Version(s)**
`1.0.0-beta.44`

**`Node.js` Version(s)**
`v14.16.1`

**Additional context**

The problem is in the `package.json` of `@redocly/openapi-cli`. Although `js-yaml` is used in that distribution (in `node_modules/@redocly/openapi-cli/lib/utils.js`, it is not mentioned in the `package.json`.

In development, this uses the `js-yaml` defined in `@redocly/openapi-core`'s `package.json` (`"js-yaml": "^3.14.0"`).

In my project, it uses whatever `js-yaml` it finds at the top level in `node_modules`, which happens to be `4.1.0`.

No, mono-repos are not a good idea.

**Comment by jandppw** [comment]
Workaround: tweak `package-lock` by hand

In the entry for `"@redocly/openapi-cli"`

- copy the `requires.js-yaml` line in the `requires` section of `"@redocly/openapi-cli"`
- copy the `dependencies.js-yaml` section of `"@redocly/openapi-core"` into the definition of `"@redocly/openapi-cli"`

and only use `npm ci`.

**Comment by jandppw** [comment]
A workaround that seems to 'work':

in `package.json`:

```
  …
  "scripts": {
    "preinstall": "scripts/workaround.js",
  },
  …
```

And create the file `scripts/workaround.js` with this content:

```
#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const packageLock = require('../package-lock.json')

const jsYaml = 'js-yaml'

console.log('Patching package-lock to work around https://github.com/Redocly/openapi-cli/issues/286 …')

const cli = packageLock.dependencies['@redocly/openapi-cli']
const core = packageLock.dependencies['@redocly/openapi-core']

cli.requires[jsYaml] = core.requires[jsYaml]
if (!cli.dependencies) {
  cli.dependencies = {}
}
Object.keys(core.dependencies).forEach(key => {
  cli.dependencies[key] = core.dependencies[key]
})

const json = JSON.stringify(packageLock, null, 2)

const packageLockPath = path.join(__dirname, '..', 'package-lock.json')
fs.writeFileSync(packageLockPath, json)

console.log('package-lock patched')
```

**Comment by jandppw** [comment]
@AntonKozachuk about "priority low"

I'm afraid that with this label this will be put this on the backburner.

I understand that your team has different priorities, and this is up to you to decide, of course.

But please consider that the time to fix this is just a few minutes: copy a line from `@redocly/openapi-core`'s `package json`:

```
  …
  "js-yaml": "^3.14.0"
  …
```

I would create a pull request for this, but I think that makes things more difficult in this case, and probably will not help you in releasing a fix earlier.

**Comment by RomanHotsiy** [comment]
I raised the priority here. We'll resolve it ASAP.
