### ISSUE TITLE
OpenApi preview-docs doesn't support 3.1

### ISSUE THREAD

**Issue by frosty110** [Redocly/openapi-cli#304]
**Describe the bug**
I know 3.1.0 is new but I love the preview-docs feature and wanted to know when it'll be supported to work with the 3.1.0 openapi spec. Thanks!

**To Reproduce**
1. Run `openapi preview-docs -p 8888 openapi.yaml`. Make sure the yaml file is on version 3.1.0
2. Go to the preview URL that's provided
3. Observe the error.

**Expected behavior**
I except no error and to see the preview docs.

**Logs**
![image](https://user-images.githubusercontent.com/4205285/119924226-08abb580-bf28-11eb-9338-ed14e93c94f2.png)

**OpenAPI definition**
Any OpenAPI file using 3.1.

**`openapi-cli` Version(s)**
Current version

**`Node.js` Version(s)**
n/a

**Comment by RomanHotsiy** [comment]
This is coming early next week. Thanks for reporting.

**Comment by adamaltman** [comment]
@RomanHotsiy we have some basic support at this time, right? Or are we waiting for something else before we close this issue?

**Comment by RomanHotsiy** [comment]
Oh, yes, we already have support in the community edition preview (you should be not logged in with cli). Pro version preview is coming soon too.

**Comment by adamaltman** [comment]
The pro version is here too. We missed closing this one. (Reopen if I'm wrong.)
