### ISSUE TITLE
Join specification with one entrypoint

### ISSUE THREAD

**Issue by prousso** [Redocly/openapi-cli#323]
**Is your feature request related to a problem? Please describe.**
We are able to lint a specification (and solve reference) with one entrypoint why not do the same for join command?

**Describe the solution you'd like**
openapi-cli join my-spec.yaml

Thanks

**Comment by RomanHotsiy** [comment]
@prousso I'm not 100% clear what is the desired behavior.

Maybe you are looking for a `bundle` command?

**Comment by prousso** [comment]
That's entirely true....
Thanks
