### ISSUE TITLE
v1.0.0-beta.55 not available on NPM

### ISSUE THREAD

**Issue by piotr-cz** [Redocly/openapi-cli#340]
**Describe the bug**
Latest version 1.0.0-beta.55 is not available in npm registry

**To Reproduce**
1. Go to https://www.npmjs.com/package/@redocly/openapi-cli
2. Look up Version on side panel
4. See 1.0.0-beta.54

**Expected behavior**
v1.0.0-beta.55 should be available to install

**Logs**
-

**OpenAPI definition**
-

**`openapi-cli` Version(s)**
-

**`Node.js` Version(s)**
-

**Additional context**
-

**Comment by andriyl** [comment]
@piotr-cz [v1.0.0-beta.55](https://www.npmjs.com/package/@redocly/openapi-cli) published
