### ISSUE TITLE
`bundle` command fails when passing `--lint --generate-ignore-file`

### ISSUE THREAD

**Issue by bandantonio** [Redocly/openapi-cli#372]
**Describe the bug**
When you execute the `bundle` command along with the `--lint` parameter, and if linter finds errors in API definitions, it shows a standard output - a summary of errors that were found and then the following recommendation:
```
- run with `--generate-ignore-file` to add all problems to ignore file.
```
But when you try to do that, you get an error:

```
openapi bundle test.yaml not-test.yaml -o ./bundled --lint --generate-ignore-file

openapi bundle [entrypoints...]

Bundle definition.

Positionals:
  entrypoints                               [array] [default: []]

Options:
      --version            Show version number.         [boolean]
      --help               Show help.                   [boolean]
  -o, --output                                           [string]
      --format             Use a specific output format.
              [choices: "stylish", "codeframe", "json"] [default:
                                                     "codeframe"]
      --max-problems       Reduce output to max N problems.
                                          [number] [default: 100]
      --ext                Bundle file extension.
                                 [choices: "json", "yaml", "yml"]
      --skip-rule          Ignore certain rules.          [array]
      --skip-preprocessor  Ignore certain preprocessors.  [array]
      --skip-decorator     Ignore certain decorators.     [array]
  -d, --dereferenced       Produce fully dereferenced bundle.
                                                        [boolean]
  -f, --force              Produce bundle output even when errors
                           occur.                       [boolean]
      --config             Specify path to the config file.
                                                         [string]
      --lint               Lint definitions
                                       [boolean] [default: false]

Unknown arguments: generate-ignore-file, generateIgnoreFile
```

**To Reproduce**

1. Run the following command: `openapi bundle test.yaml not-test.yaml -o ./bundled --lint`. You should receive the following output:

    ```
    openapi bundle test.yaml not-test.yaml -o ./bundled --lint
    test.yaml:
      14:7  error    spec                   Property `summay` is not expected here.
      15:7  error    spec                   Property `operationIds` is not expected here.
      14:7  error    operation-summary      Operation object should contain `summary` field.
      14:7  warning  operation-operationId  Operation object should contain `operationId` field.
    
    ❌ Validation failed with 3 errors and 1 warning.
    run with `--generate-ignore-file` to add all problems to ignore file.
    
    bundling test.yaml...
    📦 Created a bundle for test.yaml at bundled/test.yaml 71ms.
    not-test.yaml:
      29:11  error    spec  Property `header` is not expected here.
    
    ❌ Validation failed with 1 error.
    run with `--generate-ignore-file` to add all problems to ignore file.
    
    bundling not-test.yaml...
    📦 Created a bundle for not-test.yaml at bundled/not-test.yaml 50ms.
    ```
2. Observe the recommendation on lines 9 and 17: `run with `--generate-ignore-file` to add all problems to ignore file.`
3. Run the following command based on the recommendation: `openapi bundle test.yaml not-test.yaml -o ./bundled --lint --generate-ignore-file`
4. See error:

    ```
    openapi bundle test.yaml not-test.yaml -o ./bundled --lint --generate-ignore-file
    
    openapi bundle [entrypoints...]
    
    Bundle definition.
    
    Positionals:
      entrypoints                               [array] [default: []]
    
    Options:
          --version            Show version number.         [boolean]
          --help               Show help.                   [boolean]
      -o, --output                                           [string]
          --format             Use a specific output format.
                  [choices: "stylish", "codeframe", "json"] [default:
                                                         "codeframe"]
          --max-problems       Reduce output to max N problems.
                                              [number] [default: 100]
          --ext                Bundle file extension.
                                     [choices: "json", "yaml", "yml"]
          --skip-rule          Ignore certain rules.          [array]
          --skip-preprocessor  Ignore certain preprocessors.  [array]
          --skip-decorator     Ignore certain decorators.     [array]
      -d, --dereferenced       Produce fully dereferenced bundle.
                                                            [boolean]
      -f, --force              Produce bundle output even when errors
                               occur.                       [boolean]
          --config             Specify path to the config file.
                                                             [string]
          --lint               Lint definitions
                                           [boolean] [default: false]
    
    Unknown arguments: generate-ignore-file, generateIgnoreFile
    ```

**Expected behavior**
There are two possible (acceptable) options:
a) Do not show the recommendation that leads to erroneous behavior
b) Allow passing `--lint --generate-ignore-file` together to ensure that the shown errors are ignored properly

**OpenAPI definition**
<details>
<summary>test.yaml</summary>
<code>
<pre>
openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Information about Petstore
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /pets:
    get:
      summay: List all pets
      operationIds: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
</pre>
</code>
</details>

<details>
<summary>not-test.yaml</summary>
<code>
<pre>
openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Information about Petstore
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: An paged array of pets
          header:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
</pre>
</code>
</details>

**`openapi-cli` Version(s)**
1.0.0-beta.54

**`Node.js` Version(s)**
v14.17.0

**Comment by skadinna** [comment]
It looks like there could be another acceptable option: 
c) Correct the recommendation text 

If it currently says
` - run with --generate-ignore-file to add all problems to ignore file.`, 
we can correct it to something like 
`- run openapi lint --generate-ignore-file to add all problems to the ignore file.`

Using this parameter with the `lint` command should work.
