### ISSUE TITLE
`push` command broken in beta 59 and 60

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#377]
**Describe the bug**

openapi push (with 1.0.0-beta.60 or 1.0.0-beta.59):

> File upload failed

openapi push 

**To Reproduce**
1. Given any openapi.yaml file
2. And version 1.0.0-beta.59 or 1.0.0-beta.60
3. Run the `push` command
4. See error: 
> File upload failed

**Expected behavior**

The `push` command should work -- the same API content works with beta.58 and prior.

**Logs**

n/a

**OpenAPI definition**

I tried with a 3.0 definition.

**`openapi-cli` Version(s)**

- 1.0.0-beta.59
- 1.0.0-beta.60

**`Node.js` Version(s)**

16.1.0

**Additional context**

A thread in the support slack channel.

**Comment by HubertSzymanskiCDQ** [comment]
I've tried with version 1.0.0-beta.58 and had the same issue:
`npx @redocly/openapi-cli@v1.0.0-beta.58 push /tmp/api/API.yaml "@cdq-ag/API@V4" --upsert`
> File upload failed
Any ideas how to workaround this?

**Comment by HubertSzymanskiCDQ** [comment]
It's working with version v1.0.0-beta.57 and below.

**Comment by Marshevskyy** [comment]
> It's working with version v1.0.0-beta.57 and below.

how about v1.0.0-beta.58 and above?
it works for me

**Comment by HubertSzymanskiCDQ** [comment]
Maybe npx keeps cached wrong version? Any ideas how to force redownload package?

**Comment by AlexVarchuk** [comment]
@HubertSzymanskiCDQ  try `npm cache verify` or `npm cache clean --force`

**Comment by adamaltman** [comment]
🤷 It works for me now.

**Comment by HubertSzymanskiCDQ** [comment]
> @HubertSzymanskiCDQ try `npm cache verify` or `npm cache clean --force`

Yeah, that fixed the issue, thx!
