### ISSUE TITLE
support --region for login command

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/openapi-cli#382]
**Is your feature request related to a problem? Please describe.**
We have two regions: us and eu.

They differ by `REDOCLY_DOMAIN` url:

us: api.redoc.ly
eu: api.eu.redocly.com

See here: https://github.com/Redocly/openapi-cli/blob/master/packages/core/src/redocly/query.ts#L3

**Describe the solution you'd like**
Add support `--region` for the login command.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by adamaltman** [comment]
Good one. Default to `US`, and additional option is `EU`. But maybe there are other ways to do this? What if the API URL was an env variable with a default value of the US URL? This may give more flexibility to be able to target local/dev/and other environments too.

**Comment by RomanHotsiy** [comment]
@adamaltman it is like that right now. We have an env variable 😀

The cli flag would add alternative more user friendly approach.

**Comment by adamaltman** [comment]
I like this option. Some users won't even know their region, so... this may be the easiest for them.
