### ISSUE TITLE
`hide-x-internal` built-in decorators

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#396]
**Is your feature request related to a problem? Please describe.**

Hiding internal APIs is a common scenario.

**Describe the solution you'd like**

We have an article: https://redoc.ly/docs/cli/guides/hide-apis/ which shows how to make a decorator using `x-internal` to hide operations, paths, and schema properties. This could be improved to support parameters, etc. Also, it doesn't clean unused components (which should probably be its own built-in decorator).

**Describe alternatives you've considered**

None

**Additional context**

Related decorator ideas:

- Hide or select based on tags (for example, bundle only the customers and payments tags; or remove everything with the billing tag).

**Comment by slavikbez** [comment]
Hiding parameters: https://github.com/Redocly/openapi-cli/issues/376#issuecomment-946861306

**Comment by slavikbez** [comment]
@adamaltman should this be split to multiple decorators, like:
- hide-internal-paths
- hide-internal-operations
- hide-internal-properties
- hide-internal-parameters

**Comment by adamaltman** [comment]
I don't think so, because people will want to hide the internal things or not hide them.

**Comment by adamaltman** [comment]
However, I don't have a strong opinion either way... it just feels like too much to document.

**Comment by RomanHotsiy** [comment]
I believe a single decorator makes more sense.

**Comment by slavikbez** [comment]
I got stuck with tests here https://github.com/Redocly/openapi-cli/pull/443 and I need to switch to other more prioritised work. Maybe somebody will take over when time allows.

**Comment by bojanz** [comment]
I have just posted a related issue detailing bugs when trying to make hide-internal-parameters work: #453.

**Comment by bojanz** [comment]
Great job, everyone!

I have opened a followup bug report based on my testing of the new feature: #501.
