### ISSUE TITLE
`preview-docs` page refresh breaks with `pagination` section or item

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#423]
**Describe the bug**

When the reference docs config has:

```yaml
referenceDocs:
  pagination: section
  # or pagination: item
```

And you browse to an operation...

Then refresh the browser and voila!

**To Reproduce**
1. Given this `.redocly.yaml` file excerpt above (You can use rebilly/api-definitions core API)
2. And this OpenAPI file(s) (Use rebilly/api-definitions core API)
3. Run this command with these arguments... `openapi preview-docs core`
4. Browse to **Customers > Create a customer**.
5. Refresh the browser.
6. See error.

**Expected behavior**

It should work.

**Logs**

n/a

**`openapi-cli` Version(s)**

Latest as of Oct 28, 2021.

**`Node.js` Version(s)**
14 LTS.

**Comment by slavikbez** [comment]
@adamaltman rebilly's core api seems too heavy to run locally. In very rare cases I get page initially loaded but when I reload browser I see the loading spinner forever. Is this a problem you're talking about or it's something different?

P.S. I was trying to run `preview-docs` for storefront api and browser reloading works good there.

**Comment by slavikbez** [comment]
I was able to reproduce it. I ran it using reference-docs and when I reload the page I get: **404 Not Found**

**Comment by slavikbez** [comment]
Located the problem: https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/commands/preview-docs/preview-server/preview-server.ts#L108

**NOTE** this problem exists only with `pagination` set to `item` or `section`
