### ISSUE TITLE
Problems removing params from a decorator

### ISSUE THREAD

**Issue by bojanz** [Redocly/openapi-cli#453]
Based on the official tutorial, we have written a set of decorators for removing endpoints, params, properties, components that have "x-internal: true". This has worked well for a time, but as our schemas became more complex, we started noticing issues around parameter removal. I have now managed to produce a minimal example demonstrating the issues.

Full repository: https://github.com/bojanz/openapi-cli-bug

Let's take the following decorator:
```
   "remove-parameters": () => {
      return {
        Parameter: {
          leave(parameter, ctx) {
            if (parameter["x-internal"]) {
              ctx.parent.splice(ctx.key, 1);
            }
          },
        },
      };
    },
```

And the following parameters:
```
    parameters:
        - $ref: '#/components/parameters/Vendor'
        - in: query
          name: filter[owner_id]
          description: Allows filtering by `owner_id`.
          schema:
            type: string
        - in: query
          name: filter[external_id]
          description: Allows filtering by `external_id`.
          schema:
            type: string
          x-internal: true
        - in: query
          name: filter[deleted]
          description: Allows filtering by `deleted`.
          schema:
            type: boolean
          x-internal: true
```
With the referenced Vendor resolving to an x-interal one:
```
    Vendor:
      in: header
      name: X-Vendor
      description: The vendor.
      schema:
        type: string
      x-internal: true
```

Problems:
1) The referenced Vendor parameter is only removed from the first endpoint. It is ignored for all subsequent endpoints (decorator never called). This problem goes away if we nest the Parameter decorator under PathItem (but requires us to duplicate it for operation-level parameters). Alternatively, the problem goes away if we dereference the parameter and stop using $ref.

2) filter[external_id] gets removed but filter[deleted] doesn't (decorator not called). This might be a result of the splice call in the decorator?

Bonus observation:
It feels odd that parameter references are auto-resolved, but property references need to be resolved manually. Why isn't it automatic there as well? Performance optimization?

**Comment by bojanz** [comment]
Looking at the new built-in remove-x-internal decorator I was able to rewrite the decorator to work properly:
```
"remove-parameters": () => {
      function removeParameters(node, ctx) {
        if (!node.parameters) {
          return;
        }

        let didDelete = false;
        for (let i = 0; i < node.parameters.length; i++) {
          if (!node.parameters[i]) {
            continue;
          }
          parameter = node.parameters[i]
          if (parameter["$ref"]) {
            resolved = ctx.resolve({
              $ref: parameter["$ref"],
            });
            parameter = resolved.node;
          }
          if (parameter["x-internal"]) {
            node.parameters.splice(i, 1);
            didDelete = true;
            i--;
          }
        }
      }

      return {
        Operation: {
          leave(operation, ctx) {
            removeParameters(operation, ctx);
          },
        },
        PathItem: {
          leave(pathItem, ctx) {
            removeParameters(pathItem, ctx);
          },
        },
      };
    },
```

I think that, plus the existence of the built-in decorator mean that this issue can now be closed. Before we do that though, I'd like to know, is there a way to simplify the new code? I am not sure if there's a shorter way of accessing the resolved parameters.

**Comment by bojanz** [comment]
Came up with the slightly simpler:
```
    "remove-parameters": () => {
      function removeParameters(parameters, ctx) {
        return parameters.filter(function (parameter) {
          if (parameter["$ref"]) {
            resolved = ctx.resolve({
              $ref: parameter["$ref"],
            });
            parameter = resolved.node;
          }

          return !parameter["x-internal"];
        })
      }

      return {
        Operation: {
          leave(operation, ctx) {
            if (operation.parameters) {
              operation.parameters = removeParameters(operation.parameters, ctx);
            }
          },
        },
        PathItem: {
          leave(pathItem, ctx) {
            if (pathItem.parameters) {
              pathItem.parameters = removeParameters(pathItem.parameters, ctx);
            }
          },
        },
      };
    },
```

**Comment by RomanHotsiy** [comment]
Oh, I think we have an issue in our built-in decorator. We forgot about $ref-ed components... 🙈 
We'll fix built-in decorator soon. Your code seems valid.
