### ISSUE TITLE
Lint incorrectly reports boolean schemas for array items as invalid

### ISSUE THREAD

**Issue by shabbyrobe** [Redocly/openapi-cli#457]
**To Reproduce**
1. Given this `.redocly.yaml` file
None

2. And this OpenAPI file(s)

<details>
<summary>openapi.yml</summary>

```yml
openapi: 3.1.0

info:
  title: Bug
  version: 0.0.1
  description: "Bug"
  license:
    name: Unlicensed
    identifier: UNLICENSED
    url: http://invalid

servers:
- description: "yep"
  url: http://invalid

paths:
  /test:
    get:
      operationId: getTest
      summary: Get Test! Foo! Etc!
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                type: array
                prefixItems:
                  - type: "string"
                items: false
        400:
          description: "400"
          content:
            application/json:
              schema: { type: "object" }
```

</details>

3. Run this command with these arguments... `openapi ...`

```
npx @redocly/openapi-cli lint ~/tmp/oasbug.yml
```

```
Expected type `Schema` (object) but got `boolean`

28 |         prefixItems:
29 |           - type: "string"
30 |         items: false
31 | 400:
32 |   description: "400"
```

**Expected behavior**
This is valid according to Draft 2020-12's [test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/8d96d15fcc9c840f30360a2666c3e90b189cde2c/tests/draft2020-12/items.json#L49)

**`openapi-cli` Version(s)**
What version of `openapi-cli` are you using? 
*1.0.0-beta.69*

**`Node.js` Version(s)**
What version of `node.js` are you using?
*16.10.0*

**Comment by RomanHotsiy** [comment]
@shabbyrobe thanks for reporting.

**Comment by shabbyrobe** [comment]
This seems to apply to `unevaluatedProperties` and `unevaluatedItems` too; the same kind of error is reported.
