### ISSUE TITLE
Documentation should mention that linting does not use OAS JSON schemas

### ISSUE THREAD

**Issue by edno** [Redocly/openapi-cli#463]
The documentation should explicitly mention that `openapi-cli` linting does not use the officials OAS JSON schemas as documented [here](https://github.com/OAI/OpenAPI-Specification/tree/main/schemas). But, it rather relies on its own TS type definitions of OAS (ie loose reference to the JSON schemas).

**Comment by RomanHotsiy** [comment]
Hi @edno.

I don't think we should explicitly mention that. Json schema is just one way of validation JSON structures.
The ultimate source of truth is the specification itself.

We also have a short "What makes this tool different" section in the readme.

**Comment by edno** [comment]
@RomanHotsiy - `Json schema is just one way of validation JSON structures.`, yet OAI does not provide an official TS type definition. Hence, the current TS types are interpretations, and they have discrepancies and users should be made aware of this risk.
