### ISSUE TITLE
The `paths-kebab-case` rule also disallows paths with trailing slashes

### ISSUE THREAD

**Issue by dwilmer-karify** [Redocly/openapi-cli#465]
**Describe the bug**
The `paths-kebab-case` rule also disallows paths with trailing slashes.

**To Reproduce**
1. Given a `.redocly.yaml` containing the following rule options:
    ```
    no-path-trailing-slash: off
    paths-kebab-case: error
    ```
2. And an openapi.yml file containing a path with a trailing slash, e.g. `/accounts/`
3. Run `openapi lint openapi.yml`
4. It produces an error about the path not being kebab-case

**Expected behavior**
I expect the openapi.yml` file to be considered valid.

**Logs**
n/a

**OpenAPI definition**
OpenAPI version 3.0

**`openapi-cli` Version(s)**
v1.0.0-beta69

**`Node.js` Version(s)**
_Not relevant_

**Additional context**
The problem is in the regular expressions that are used in the [paths-kebab-case rule](https://github.com/Redocly/openapi-cli/blob/v1.0.0-beta.69/packages/core/src/rules/common/paths-kebab-case.ts). In this rule, the path is split up in segments delimited by the slash (`/`). When a path contains a trailing slash, this produces an empty segment.
The regular expressions then test for either a segment within curly brackets for an ID (`/^{.+}/$`), or a segment of one or more lowercase alphanumeric characters, hypens, or dots (`/^[a-z0-9-.]+$/`). To allow for empty segments (e.g. when a path contains a trailing slash), this last regular expression should be changed to `/^[a-z0-9-.]*$/`.

**Comment by RomanHotsiy** [comment]
Opened a PR here: https://github.com/Redocly/openapi-cli/pull/466

I'll add tests and will merge it later this week.

Thanks for the report!

**Comment by dwilmer-karify** [comment]
Awesome! Thanks for picking this up so quickly!
