### ISSUE TITLE
enable-rule, enable-decorator args

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#495]
**Is your feature request related to a problem? Please describe.**

There is a way to skip rules and decorators but no way to enable them by args.

I think this causes a user experience problem. This means to enable any decorator or rule requires adding it explicitly to the `.redocly.yaml` file. This is problematic when someone doesn't even have a `.redocly.yaml` file -- they need to:

1. Create a `.redocly.yaml` file (which has its own challenges because commonly used operating systems hide dot files by default)
2. Learn the structure of the file and fill it out to enable a rule or decorator. Save the file.
3. Commit to source control, upload, or CLI push again.

**Describe the solution you'd like**

I would like to be able to specify enabling some rule or decorator at runtime. For example, removing internal APIs.... 

`--enable-decorator=remove-x-internal,remove-unused-components`

**Describe alternatives you've considered**

Auto-generating `.redocly.yaml` file on the fly from a wizard.

**Additional context**

I am envisioning what the usage may be like from within the API registry in workflows, where someone may be able to select from specific rules and decorators.

**Comment by adamaltman** [comment]
This one needs some thought. I'm not coming into this with certainty in this solution.

See here for some other context: https://github.com/Redocly/openapi-cli/pull/443#pullrequestreview-842344756

**Comment by RomanHotsiy** [comment]
I'm not sure about `--enable-rule` as rules have to have a severity specified while a decorator may be just turned on.

**Comment by andriyl** [comment]
Suggestions about parameters:
`--enable-decorator=remove-x-internal{key:value},remove-unused-components`
`--enable-decorator=remove-x-internal@key:value,key2:value2,remove-unused-components`

**Comment by adamaltman** [comment]
Thank you @andriyl  -- I like the `{key:value,key2:value2}`. But, don't proceed yet -- let's get more feedback.

**Comment by RomanHotsiy** [comment]
> As it turns out this issue exists for decorators and rules.

Do you mean ability to enable rule from CLI? or ability to specify options via CLI? Could you elaborate?

**Comment by andriyl** [comment]
I suggest using space instead of ` , ` when passing the list of decorators or rules.
`--enable-decorator=remove-x-internal remove-unused-components
` as a result, we get here: 
`[ 'remove-x-internal', 'remove-unused-components' ]`.

Otherwise using `coma`: `[ 'remove-x-internal,remove-unused-components' ]`

**Comment by adamaltman** [comment]
This might also be solved with further improvements to the config format (started here: #87 ).

**Comment by RomanHotsiy** [comment]
I think it should be closed after we updated redocly.yaml file format. @adamaltman what do you think?

**Comment by RomanHotsiy** [comment]
This was resolved by https://github.com/Redocly/openapi-cli/pull/588.

Someone can create multiple entrypoints with different decorators setup.
