### ISSUE TITLE
$ref not supported in parameters

### ISSUE THREAD

**Issue by benasher44** [Redocly/openapi-cli#543]
**Describe the bug**
I'm attempting to declare a parameter that has a schema attribute with a ref, like so:
```yaml
name: cursor
in: body
required: false
schema:
  $ref: '#/components/schemas/cursor'
```
Unfortunately, this seems to not work with redocly-cli. As best as I can tell, this is supported by the OpenAPI spec.

**To Reproduce**
1. Given the attached multi-file openapi setup
2. Run `openapi bundle openapi.yml`

**Expected behavior**
Bundles the openapi spec without error

**Logs**
```
Can't resolve $ref

3 | required: false
4 | schema:
5 |   $ref: '#/components/schemas/cursor'
```

**OpenAPI definition**
[openapi.zip](https://github.com/Redocly/openapi-cli/files/7990896/openapi.zip)

**`openapi-cli` Version(s)**
[1.0.0-beta.80](https://www.npmjs.com/package/@redocly/openapi-cli/v/1.0.0-beta.80)

**`Node.js` Version(s)**
16.13.0

**Additional context**
The attached project is very work-in-progress-y, so I've commented out pieces of it to narrow down to the core piece that's failing to validate, which I believe is what's cascading into failures elsewhere.

**Comment by benasher44** [comment]
Btw, I'm really excited about redocly's openapi-cli project! Hoping to use it to codify [Ashby's API](https://developers.ashbyhq.com/)

**Comment by RomanHotsiy** [comment]
@benasher44 thanks!

I believe this may be resolved already but not released. We'll check it soon and will cut a release if needed.

**Comment by benasher44** [comment]
Awesome—thanks!!

**Comment by RomanHotsiy** [comment]
@benasher44 oh, sorry I meant to answer this to you in the other issue. Regarding this one. You are not using a valid pointer: `#` means relative to the current document (i.e. file).

To fix this you have to use:

```
name: cursor
in: body
required: false
schema:
  $ref: '../schemas/properties/cursor.yml'
```

**Comment by benasher44** [comment]
Ah! My mistake. Thanks!
