### ISSUE TITLE
Cannot find module 'https-proxy-agent'

### ISSUE THREAD

**Issue by diegoNutmeg** [Redocly/openapi-cli#555]
**Describe the bug**
Today the cli is starting reporting an error in a sub-dependency, breaking the execution.

**To Reproduce**
1.  `npx @redocly/openapi-cli@1.0.0-beta.32 `lint path-to-root-file.yaml`

**Expected behavior**

**Logs**
```
npx: installed 99 in 8.928s
Cannot find module 'https-proxy-agent'
Require stack:
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/registry-api.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/index.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/config/load.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/index.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/lib/utils.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/lib/assert-node-version.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/lib/index.js
- /home/jenkins/.npm/_npx/240/lib/node_modules/@redocly/openapi-cli/bin/cli.js
```

**OpenAPI definition**
If applicable, add an OpenAPI definition and `.redocly.yaml` configuration file that helps reproduce the problem.
At a minimum, please state the specification version(s) you're using (e.g. 2.0, 3.0, 3.1).

**`openapi-cli` Version(s)**
1.0.0-beta.32

**`Node.js` Version(s)**
nodejs 14, nodejs 16

**Comment by tatomyr** [comment]
Hi @diegoNutmeg,
Thank you for reporting the issue. Could you check again with **node 16**? Looks like it should work, or it could be a caching issue. 
Also, for the latest version (currently **1.0.0-beta.81**) this should work for both **node 14 & 16**.

**Comment by diegoNutmeg** [comment]
Thanks @tatomyr 
We still experience issues with the version `1.0.0-beta.32`.
We are gonna try to test it with the latest version `1.0.0-beta.81`

**Comment by diegoNutmeg** [comment]
Worked with the `1.0.0-beta.81`
🥳

**Comment by anthonymejia** [comment]
@tatomyr this is still happening if you import openapi-core `1.0.0-beta.81`
