### ISSUE TITLE
bundle issue when files use multiple dots

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#560]
We're having a similar issue, in that our object files are named `foo.bar.baz.v1.yaml` - we've verified that the bundler behaves sensibly if we rename the files/references to `foo-bar-baz-v1.yaml`, however it would be nice(r) for the bundler not to assume that the first period it encounters is the filename and everything after it is the extension.

As it is, `foo.bar.baz.v1.yaml`, `foo.bar.qux.v1.yaml` and `foo.quux.quuz.v1.yaml` get folded into the components collection as `foo-1`, `foo-2` and `foo-3` - along with a load of "duplicate name" errors.

_Originally posted by @jasonbstanding in https://github.com/Redocly/openapi-cli/issues/260#issuecomment-1041396491_

**Comment by jasonbstanding** [comment]
Would it do the trick to change https://github.com/Redocly/openapi-cli/blob/master/packages/core/src/ref-utils.ts#L63 to:
`
const fparts = parts[parts.length - 1].split('.');
return fparts[fparts.length - 1];
`
?

**Comment by jasonbstanding** [comment]
I *think* the line involved is https://github.com/Redocly/openapi-cli/blob/964c2ba7974f9b84a3c0361eef1c599583f30298/packages/core/src/ref-utils.ts#L63 - but I'm too much of a n00b at node stuff to prove it locally right now, otherwise I'd contribute a pull request.
