### ISSUE TITLE
@AlexVarchuk

### ISSUE THREAD

**Issue by acun87** [Redocly/openapi-cli#592]
@AlexVarchuk 
Unfortunately the same issue occurs using v0.13.6

_Originally posted by @gaz77a in https://github.com/Redocly/redoc/issues/1884#issuecomment-1023712305_

**Comment by AlexVarchuk** [comment]
@acun87 Hi! Do you use `openapi-cli` or `redoc-cli`?

**Comment by acun87** [comment]
Redoc

**Comment by RomanHotsiy** [comment]
This is wrong project.
