### ISSUE TITLE
Add codeclimate output format to lint command

### ISSUE THREAD

**Issue by cykl** [Redocly/openapi-cli#650]
**Is your feature request related to a problem? Please describe.**

I would like to integrate the output `openapi lint to our merge request reports. Proprietary JSON & checkstyle output are not supported by Gitlab and would require a translation step.  

**Describe the solution you'd like**

Gitlab supports codeclimate format. I would be nice to add it to supported output formats

 - https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool
 - https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

Basic implementation should be easy and avoid users having to implement their own mapping steps.
 
**Describe alternatives you've considered**

 * Adhoc translation from json / checkstyle format to codestyle format.
 * redocly could provide a tool to translate its JSON format to codeclimate format.

**Comment by adamaltman** [comment]
It looks like Gitlab implements a subset of Code Climate. 

> A severity string (can be info, minor, major, critical, or blocker).

How would you map: `error`, `warn` to those severity strings?

Also, what value to put for the fingerprint? The rule name? Or something else?

**Comment by RomanHotsiy** [comment]
@adamaltman I would use rule name + JSON Pointer of the issue as the fingerprint.

As for the severity looks like GitLab marks anything above critical with red color and anything above minor with yellow:

![image](https://user-images.githubusercontent.com/3975738/164160416-0ab00919-3e46-4756-80d1-4920936befe2.png)


So I would map `error` to `critical` and `warn` to `minor`.

**Comment by RomanHotsiy** [comment]
Found a better picture: 
![image](https://user-images.githubusercontent.com/3975738/164160992-47f5fe86-5a5b-4acc-b639-a691945d1778.png)

**Comment by cykl** [comment]
As a disclaimer; I'm not a code climate or Gitlab expert nor have not really dig into the topic yet. I'm mostly trying to figure out how to glue two great tools together.

> I would use rule name + JSON Pointer of the issue as the fingerprint.

:+1:  Fingerprint seems to have the same usage than your ignore file. Rule name + JSON pointer would exactly match ignore file content.

> How would you map: error, warn to those severity strings?

I'm always uncomfortable with tools exposing so many severity. They always seems quite subjective and hardly actionable (would really someone react differently to a major from a critical?). My personal bias is to handle any problem as an error and configure tools to not raise false positive or explicitly ignore them.

That being said, openapi-cli returns non 0 exit code when their is at least one error and 0 otherwise. It could mean that error must be critical or blocker, and warn must but minor or major. I would not use blocker. Choosing between minor and major is harder. I think it depends you think that warns are mostly "style" issues or point issues out that should be fixed.

**Comment by adamaltman** [comment]
Makes sense. I think it should be:

error = critical
warn = minor 

The fingerprint idea is good.

**Comment by cykl** [comment]
I have not idea of how the Priority: Medium tag could translate time-wise. Could you provide a ballpark ETA? (days / weeks / months / years is likely good enough).

I'm trying to figure out if it makes sense to ask one of our node / typescript developer to give it a shoot or if it is more efficient to let you work on that.

**Comment by adamaltman** [comment]
What's a score in years? Just kidding... 🤣 I would guess 3 weeks - 2 months.

We are in the process of:
- [community rules](https://github.com/Redocly/openapi-cli/pull/616)
- [improving the assertions syntax](https://github.com/Redocly/openapi-cli/pull/662)
- adding an additional assertion option to [enforce $refs usage](https://github.com/Redocly/openapi-cli/issues/648)
- renaming to Redocly CLI 🌮 🎉 

Of course, we would welcome any [contributions](https://github.com/Redocly/openapi-cli/blob/master/.github/CONTRIBUTING.md).

**Comment by cykl** [comment]
Thanks. We wrote a patch that we are currently testing and should open a pull request soon.

**Comment by tatomyr** [comment]
Hi @cykl,
JFYI, the changes have been already published and should be available under `v1.0.0-beta.95`.
