### ISSUE TITLE
Add support for Windows development

### ISSUE THREAD

**Issue by rkrauskopf** [Redocly/openapi-cli#75]
Currently, the project does not work if you try to develop on a Windows operating system.

**Comment by knidarkness** [comment]
Thank you for your information, @rkrauskopf. I will check this ASAP.

**Comment by rkrauskopf** [comment]
Thank you!

**Comment by adamaltman** [comment]
I think this may be fixed now. @RomanHotsiy can you please confirm?

**Comment by hicksjacobp** [comment]
I'm not sure what the original issue was, but I am having issues on Windows as well. To demonstrate, I created a brand new API specification with the defaults:

<details>
<summary>Click to see details</summary>

```bash
❯ npx create-openapi-repo
Welcome to the OpenAPI-Repo generator!
? Do you already have an OpenAPI/Swagger 3.0 definition for your API? No
? API Name: redocly-test
? Prepare manual code samples folder? No
? The following folders will be created: openapi and docs
You can change them by running create-openapi-repo <openapiDir> <docsDir>
Proceed? Yes

Creating a new OpenAPI repo in C:\repos\redocly-test

Installing packages. This might take a couple of minutes.

+ @redocly/openapi-cli@1.0.0-beta.11
added 86 packages from 137 contributors and audited 87 packages in 10.249s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Initialized empty Git repository in C:/repos/redocly-test/.git/


Success! Created openapi folder.
You can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the definition.

  npm test
    Validates the definition.

We suggest that you begin by typing:

  npm start
```

</details>

With building, it produces a `dist.yaml` which contains improper references to components (just a snippet is shown):

```yaml
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/C:\repos\redocly-test\openapi\components\schemas\User
              example:
                username: user1
                email: user@example.com
```

**Comment by adamaltman** [comment]
Thanks for the report, @hicksjacobp ...

**Comment by Blacklands** [comment]
I just saw this, and since I'm also on Windows I checked as well.
I'm having the same problem as @hicksjacobp reports. This also happens when using the `openapi bundle` command on any multi-file specification (for YAML at least, I don't know about JSON).

**Comment by hicksjacobp** [comment]
Thanks for fixing this quickly! When can a new build be expected? Also, is there timeline or remaining issues list for the 1.0 release?

**Comment by RomanHotsiy** [comment]
@hicksjacobp released beta.12.

We're just waiting to get some more feedback on this release. We hope to publish 1.0 soon.

**Comment by adamaltman** [comment]
Also, I'll open a roadmap to a release candidate and then a general release version 1 tracking issue for transparency.

We make [Redoc](https://github.com/redocly/redoc) and plan to gain feedback from the Redoc community prior to the general release.

**Comment by adamaltman** [comment]
I opened the release/roadmap tracking issue here: https://github.com/Redocly/openapi-cli/issues/203
