### ISSUE TITLE
Identically named rules get overwritten.

### ISSUE THREAD

**Issue by rkrauskopf** [Redocly/openapi-cli#76]
If a user accidentally gives a custom rule a name that already exists then it gets overwritten and never runs. A note in the docs or a warning message would be helpful.

**Comment by knidarkness** [comment]
Thank you, @rkrauskopf. That definitely makes sense for me.

**Comment by RomanHotsiy** [comment]
@knidarkness I would print an error. I think such situation is not a warning

**Comment by knidarkness** [comment]
@RomanHotsiy, I agree that we could throw an error for that. Also, README should be updated.

**Comment by adamaltman** [comment]
I'm pretty sure this is solved in #146 (but I'm not 100% sure). Custom rules are namespaced.

**Comment by adamaltman** [comment]
This only applies to custom plugins since we have added the namespacing. I think we can adjust the docs there. Also, we should consider can two plugins have the same name as long as they have different rules? And we throw an error on the fully namespaced preprocessor/rule/decorator name collision?
