### ISSUE TITLE
Be able to override the context when creating an error.

### ISSUE THREAD

**Issue by rkrauskopf** [Redocly/openapi-cli#82]
I'm encountering situations where I would like to override the context and pass in my own node to specify a line number when creating an error using `ctx.createError`. Is there an easy way to do this that I've missed?

**Comment by adamaltman** [comment]
I'm wondering what the use case is for this one?

**Comment by RomanHotsiy** [comment]
This can be closed, we have a new API on the 1.0.0-beta.x which I believe covers the use case.
